from fastapi import APIRouter
from app.api.api_v1.endpoints import auth, workouts, biometrics, ai, sync, settings, readiness, readiness_ws, sessions, strava, memory, notifications, notifications_ws, community, planner, nutrition, recovery, analytics, athlete_profile, training_plans, daily_loop, dashboard, master_plan, interventions

api_router = APIRouter()

api_router.include_router(auth.router, prefix="/auth", tags=["auth"])
api_router.include_router(strava.router, prefix="/strava", tags=["strava"])
api_router.include_router(workouts.router, prefix="/workouts", tags=["workouts"])
api_router.include_router(biometrics.router, prefix="/biometrics", tags=["biometrics"])
api_router.include_router(readiness.router, prefix="/readiness", tags=["readiness"])
api_router.include_router(readiness_ws.router, prefix="", tags=["websocket"])
api_router.include_router(notifications_ws.router, prefix="", tags=["websocket"])
api_router.include_router(ai.router, prefix="/ai", tags=["ai"])
api_router.include_router(sync.router, prefix="/sync", tags=["sync"])
api_router.include_router(notifications.router, prefix="/notifications", tags=["notifications"])
api_router.include_router(settings.router, prefix="/settings", tags=["settings"])
api_router.include_router(sessions.router, prefix="/sessions", tags=["sessions"])
api_router.include_router(memory.router, prefix="/memory", tags=["memory"])
api_router.include_router(community.router, prefix="/community", tags=["community"])
api_router.include_router(planner.router, prefix="/planner", tags=["planner"])
api_router.include_router(nutrition.router, prefix="/nutrition", tags=["nutrition"])
api_router.include_router(recovery.router, prefix="/recovery", tags=["recovery"])
api_router.include_router(analytics.router, prefix="/analytics", tags=["analytics"])
api_router.include_router(athlete_profile.router, prefix="/athlete-profile", tags=["athlete-profile"])
api_router.include_router(training_plans.router, prefix="/plans", tags=["training-plans"])
api_router.include_router(daily_loop.router, prefix="/daily", tags=["daily-loop"])
api_router.include_router(dashboard.router, prefix="/dashboard", tags=["dashboard"])
api_router.include_router(master_plan.router, prefix="/master-plan", tags=["master-plan"])
api_router.include_router(interventions.router, prefix="/interventions", tags=["interventions"])
